### ISSUE TITLE
Default value for analyze_on_clock inconsistent between timewindowmatrix and timewindowanalyzer

### ISSUE THREAD

**Issue by hrabalp** [LibertyAces/BitSwanPump#33] opened 2019-08-18 21:34 UTC
https://github.com/LibertyAces/BitSwanPump/blob/1b654b985000f136fde2e9f44e544bac78866d47/bspump/analyzer/timewindowmatrix.py#L46

https://github.com/LibertyAces/BitSwanPump/blob/1b654b985000f136fde2e9f44e544bac78866d47/bspump/analyzer/timewindowanalyzer.py#L67

timewindowanalyzer have default value  analyze_on_clock=False, but timewindowmatrix have default value clock_driven=True,
While meaning is somewhat different this should still be unified to prevent confusion when inicialized separately (usualy when analyzer is not wall clock driven than matrix wont be as well)

**Comment by ateska** [comment] 2019-08-21 08:40
`analyze_on_clock` and `clock_driven` has two different meanings, they cannot be unified.

@margirova - please check the documentation if the the proper explanation is there.

**Comment by ateska** [comment] 2019-08-21 09:02
@margirova @hrabalp - the argumentation here is that the default combination `analyze_on_clock=False` and `clock_driven=True` doesn't make sense.

Correct?

**Comment by margirova** [comment] 2019-08-21 09:10
@ateska for me it totally makes sense, because it may not analyze, but still move forward, which is intended behavior. But I'll wait for counterarguments

**Comment by hrabalp** [comment] 2019-08-21 10:13
@ateska @margirova 
exactly as ales mentioned
when you are not using wall clock for analyze than it very likely you are usign some diferent timesource and that timesource is unlikely to be in sync , you allways need analyze and matrix on same clocking
it do not matter if its event or wall clock., having mismatch makes no sense

**Comment by margirova** [comment] 2019-09-13 08:53
resolved in master, will be available here soon

**Closed by margirova** 2019-09-13 08:53 UTC
